import { DEFAULT_CONFIG, HEROES, LOADOUTS, LIVERIES } from '../game/campaign';
import { MAPS } from '../game/maps';
import { honorCollection } from './battle-honors';
import { icon } from './visuals';
import type { GameMode, GameState, HeroId, LiveryId, LoadoutId, MapId, Profile, RunConfig } from '../game/types';

export const MODE_NAMES:Record<GameMode,string>={campaign:'เนื้อเรื่อง',veteran:'ท้าทาย',endless:'ไม่สิ้นสุด',challenge:'6 ป้อม'};
const modeHints:Record<GameMode,string>={campaign:'10 เวฟ · เอาชนะบอส',veteran:'ศัตรูแกร่งขึ้น · รูปแบบบุกใหม่',endless:'เกิน 10 เวฟ · จบเพื่อเก็บคะแนนได้ระหว่างเวฟ',challenge:'สูงสุด 6 ป้อม · Bolter / Lascannon / Barracks'};
const mapIds:MapId[]=['foundry','crossroads','wastes'];
const mapHints:Record<MapId,string>={foundry:'สลับเส้นทางศัตรู',crossroads:'ป้องกัน 2 ประตู',wastes:'ยึดฐานเพื่อปลดป้อมเพิ่ม'};
const heroRoles:Record<HeroId,string>={captain:'แนวหน้า',techmarine:'ซ่อมแซม',librarian:'เวทหมู่'};
const heroSkills:Record<HeroId,string>={captain:'ฟื้นเลือด + โจมตีรอบตัว',techmarine:'ซ่อมทหาร + เร่งยิงป้อม',librarian:'โจมตีหมู่ + สโลว์'};
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function miniMap(id:MapId){
 const map=MAPS[id],points=map.paths.flat().concat(map.pads),xs=points.map(p=>p.x),zs=points.map(p=>p.z),minX=Math.min(...xs)-2,minZ=Math.min(...zs)-2,w=Math.max(...xs)-minX+2,h=Math.max(...zs)-minZ+2;
 return `<svg class="mission-terrain" viewBox="${minX} ${minZ} ${w} ${h}" aria-hidden="true">${map.paths.map(path=>`<polyline points="${path.map(p=>`${p.x},${p.z}`).join(' ')}" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/>`).join('')}${map.pads.map((p,i)=>`<circle cx="${p.x}" cy="${p.z}" r=".8" fill="${map.lockedPads.includes(i)?'#68797c':'#e8c77f'}" stroke="#162022" stroke-width=".3"/>`).join('')}${map.paths.map(path=>{const p=path[path.length-1];return `<rect x="${p.x-1}" y="${p.z-1}" width="2" height="2" fill="#99e2ce"/>`}).join('')}</svg>`;
}
export function campaignMarkup(profile:Profile,saved:GameState|null,config:RunConfig=DEFAULT_CONFIG){
 const map=MAPS[config.map],record=profile.best[`${config.map}:${config.mode}`],advanced=profile.completed.length>0;
 const ready=profile.heroes.includes(config.hero)&&profile.loadouts.includes(config.loadout)&&profile.liveries.includes(config.livery)&&(config.map==='foundry'||profile.completed.includes(mapIds[mapIds.indexOf(config.map)-1]))&&(config.mode==='campaign'||advanced);
 return `<div class="campaign-shell readable-campaign">
 <header class="campaign-header"><div><span class="eyebrow">TOWER DEFENSE</span><h1>BASTION <span>LAST STAND</span></h1></div><div class="campaign-wallet"><div>${icon('coin')}<strong>${profile.medals}</strong><span>เหรียญ</span></div><button class="tool-button" data-action="settings" aria-label="ตั้งค่าและวิธีเล่น">${icon('gear')}</button></div></header>
 <div class="campaign-layout"><section class="campaign-atlas" aria-labelledby="campaign-map-title"><div class="atlas-heading"><span class="step-number">1</span><h2 id="campaign-map-title">เลือกด่าน</h2></div><div class="mission-nodes">${mapIds.map((id,i)=>{
 const m=MAPS[id],open=i===0||profile.completed.includes(mapIds[i-1]),stars=profile.best[`${id}:campaign`]?.stars??0;
 return `<button class="mission-node mission-${id}${config.map===id?' selected':''}" data-map="${id}" aria-pressed="${config.map===id}" ${open?'':`disabled aria-label="${esc(m.name)} · ผ่านด่านก่อนหน้าเพื่อปลดล็อก"`}><span class="mission-index">0${i+1}<span>${!open?icon('lock'):config.map===id?'✓':''}</span></span>${miniMap(id)}<span class="mission-name">${esc(m.name)}</span><span class="mission-subtitle">${mapHints[id]}</span><span class="mission-stars" aria-label="${stars} จาก 3 ดาว">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</span></button>`}).join('')}</div>
 <div class="quick-guide" aria-label="วิธีเล่นแบบย่อ"><span>${icon('bolter')}<b>วางป้อม</b></span>${icon('arrow')}<span>${icon('damage')}<b>หยุดศัตรู</b></span>${icon('arrow')}<span>${icon('shield')}<b>รักษาฐาน</b></span></div>${honorCollection(profile,config.map)}</section>
 <section class="deployment-panel" aria-labelledby="deployment-title"><div class="atlas-heading"><span class="step-number">2</span><h2 id="deployment-title">เลือกฮีโร่</h2></div>
 <fieldset class="campaign-options hero-options"><legend class="sr-only">ฮีโร่</legend>${(Object.keys(HEROES) as HeroId[]).map(id=>{const h=HEROES[id],owned=profile.heroes.includes(id);return `<div class="choice-item ${config.hero===id?'selected':''}"><button class="campaign-choice hero-${id}" data-hero="${id}" aria-pressed="${config.hero===id}" ${owned?'':'disabled'}><span class="hero-portrait">${icon(id==='captain'?'helmet':id==='techmarine'?'gear':'overcharge')}</span><strong>${h.name}</strong><span>${heroRoles[id]}</span>${config.hero===id?'<i class="choice-check" aria-hidden="true">✓</i>':''}</button>${!owned?`<button class="unlock-choice" data-unlock="${id}" data-category="hero" ${profile.medals<h.cost?'disabled':''}>${icon('lock')} ${h.cost} เหรียญ</button>`:''}</div>`}).join('')}</fieldset>
 <p class="selected-hero-skill">${icon('overcharge')}${heroSkills[config.hero]}</p>
 <details class="campaign-details hero-details"><summary>ดูสกิลและระยะ</summary><p>${config.hero==='captain'?'ฟื้นเลือด Captain 100 และทหารรอบจุดเป้าหมาย 60 พร้อมโจมตี 120':config.hero==='techmarine'?'ซ่อมฮีโร่และทหาร 120 · ฟื้นป้อมที่ดับและเร่งยิง 6 วิ':'โจมตีเจาะเกราะ 260 และสโลว์ 2 วิ'}</p><p>เล็งได้ในระยะ 7 · พื้นที่สกิล 3${config.hero==='techmarine'?' · ซ่อมป้อมในระยะ 4':''}</p></details>
 <fieldset class="mode-options"><legend>โหมด</legend>${(Object.keys(MODE_NAMES) as GameMode[]).map(mode=>`<button data-mode="${mode}" aria-pressed="${config.mode===mode}" ${mode==='campaign'||advanced?'':'disabled'}>${MODE_NAMES[mode]}${mode!=='campaign'&&!advanced?icon('lock'):''}</button>`).join('')}</fieldset><p class="mode-description">${modeHints[config.mode]}</p>
 <details class="deployment-customize campaign-details"><summary>อุปกรณ์และสีเกราะ</summary><fieldset class="campaign-options"><legend>อุปกรณ์เริ่มต้น</legend>${(Object.keys(LOADOUTS) as LoadoutId[]).map(id=>{const l=LOADOUTS[id],owned=profile.loadouts.includes(id);return `<div class="choice-item ${config.loadout===id?'selected':''}"><button class="campaign-choice" data-loadout="${id}" aria-pressed="${config.loadout===id}" ${owned?'':'disabled'}><strong>${id==='balanced'?'สมดุล':id==='fortified'?'ฐานแกร่ง':'เงินนำหน้า'}</strong><span>${icon('coin')}${l.money} ${icon('shield')}${20+l.gateBonus}</span></button>${!owned?`<button class="unlock-choice" data-unlock="${id}" data-category="loadout" ${profile.medals<l.cost?'disabled':''}>${l.cost} เหรียญ</button>`:''}</div>`}).join('')}</fieldset><fieldset class="campaign-options livery-options"><legend>สีเกราะ</legend>${(Object.keys(LIVERIES) as LiveryId[]).map(id=>{const l=LIVERIES[id],owned=profile.liveries.includes(id);return `<div class="choice-item ${config.livery===id?'selected':''}"><button class="campaign-choice" data-livery="${id}" aria-pressed="${config.livery===id}" ${owned?'':'disabled'}><i class="livery-swatch" style="--livery:#${l.color.toString(16).padStart(6,'0')}"></i><strong>${id==='crimson'?'แดง':id==='cobalt'?'น้ำเงิน':'งาช้าง'}</strong></button>${!owned?`<button class="unlock-choice" data-unlock="${id}" data-category="livery" ${profile.medals<l.cost?'disabled':''}>${l.cost} เหรียญ</button>`:''}</div>`}).join('')}</fieldset></details>
 ${record?`<p class="mission-record">${'★'.repeat(record.stars)} · สถิติ ${record.score.toLocaleString()}</p>`:''}
 <div class="deployment-actions">${saved?`<button class="button continue-button" data-action="continue">เล่นต่อ ${icon('arrow')}<small>${esc(MAPS[saved.config.map].name)} · เวฟ ${saved.wave} · เริ่มแบบพักเกม</small></button>`:''}<button class="button primary deploy-button" data-action="begin" ${ready?'':'disabled'}>${saved?'เริ่มรอบใหม่':'เริ่มป้องกัน'} ${icon('arrow')}</button>${saved?'<p class="save-note">รอบใหม่จะแทนที่เกมที่บันทึกไว้</p>':'<p class="save-note">บันทึกอัตโนมัติ</p>'}</div>
 </section></div><footer class="campaign-footer"><span>WARHAMMER 40,000 · FAN GAME</span><span>Unofficial · Not affiliated with Games Workshop</span></footer></div>`;
}
